"""fix_created_at_default

Revision ID: 57a83f9ef5ba
Revises: 45112eedba89
Create Date: 2026-05-05 14:42:14.395451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '57a83f9ef5ba'
down_revision: Union[str, Sequence[str], None] = '45112eedba89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('todos', 'is_completed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('todos', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('todos_user_id_fkey'), 'todos', type_='foreignkey')
    op.create_foreign_key(None, 'todos', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todos', type_='foreignkey')
    op.create_foreign_key(op.f('todos_user_id_fkey'), 'todos', 'users', ['user_id'], ['id'])
    op.alter_column('todos', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('todos', 'is_completed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('todos', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
