"""add_server_default_to_todo

Revision ID: 58c3f3e52f18
Revises: 57a83f9ef5ba
Create Date: 2026-05-05 14:45:22.019447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58c3f3e52f18'
down_revision: Union[str, Sequence[str], None] = '57a83f9ef5ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
